---
title: Space Babies
baseURL: "https://www.spacebabies.nl/"
defaultContentLanguage: en
languageCode: en-us
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true
# We do redirects via Netlify
disableAliases: true
ignoreErrors:
  - error-remote-getjson
taxonomies:
  category: categories
  tag: tags
  changelog: changelog
  series: series
menu:
  header:
    - name: About me
      URL: "/#about"
      weight: 2
    - name: Portfolio
      URL: "/#portfolio"
      weight: 3
    - name: Contact
      URL: "/#contact"
      weight: 4
  footer:
    - name: About me
      URL: "/#about"
      weight: 2
    - name: Portfolio
      URL: "/#portfolio"
      weight: 3
    - name: Contact
      URL: "/#contact"
      weight: 4
module:
  mounts:
    - source: node_modules/animate.css
      target: assets/animate.css
    - source: assets
      target: assets
    - source: node_modules/@fontsource/inter/files
      target: static/fonts/inter
    - source: static
      target: static
params:
  colors:
    tile: "#603cba"
    theme: "#cac8c7"
  description: "I create websites in Ruby on Rails and HTML, CSS, and Javascript (Jamstack)"
  images:
    - /img/space-babies.png
  title: Space Babies
  shortname: spacebabies
  sections:
    - about
    - experience
    - client-and-work
    - contact
  mainSections:
    - changelog
  logo:
    text1: Space
    text2: Babies
  theme:
    color: "#cac8c7"
  streetAddress: Overhoeksplein 2
  addressLocality: Amsterdam
  postalCode: NL-1031KS
  addressCountry: NL
  email: info@spacebabies.nl
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true
markup:
  goldmark:
    renderer:
      unsafe: true
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
server:
  headers:
    - for: /site.webmanifest
      values:
        Content-Type: application/manifest+json; charset=UTF-8
outputs:
  home:
    - HTML
    - RSS
    - JSON
