---
baseURL: 'https://www.spacebabies.nl/'
defaultContentLanguage: en
languageCode: en-us
theme: raditian-free-hugo-theme
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
taxonomies:
  category: categories
  tag: tags
  changelog: changelog
  series: series
menu:
  header:
    - name: About me
      URL: '#about'
      weight: 2
    - name: Portfolio
      URL: '#portfolio'
      weight: 3
    - name: Contact
      URL: '#contact'
      weight: 4
  footer:
    - name: About me
      URL: '#about'
      weight: 2
    - name: Portfolio
      URL: '#portfolio'
      weight: 3
    - name: Contact
      URL: '#contact'
      weight: 4
params:
  description: 'I create websites in Ruby on Rails and HTML, CSS, and Javascript (Jamstack)'
  images:
    - /img/space-babies.png
  title: Space Babies
  shortname: spacebabies
  sections:
    - flash
    - showcase
    - about
    - experience
    - client-and-work
    - testimonial
    - contact
  mainSections:
    - changelog
  logo:
    text1: Space
    text2: Babies
  theme:
    color: "#cac8c7"
  footer:
    copyright: KvK 70132208
    radity_logo:
      x: /img/general/design-and-code-radity.png
      _2x: /img/general/design-and-code-radity@2x.png
      alt: Design & Code - Radity
markup:
  goldmark:
    renderer:
      unsafe: true
