baseURL = "/"
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "Space Babies"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Internet Engineers. If you can envision it, we can build it."
  copyright = "Overhoeksplein 2<br>NL-1031KS Amsterdam<br>The Netherlands<br><br>KvK 70132208<br>VAT NL147480140B02<br><br><br>"
  sidebarAbout = ["We create beautiful, fast and secure web applications."]
  images = ["img/space-babies.png"]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "joost@spacebabies.nl"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "info@spacebabies.nl"
  stackoverflow = "https://stackoverflow.com/users/235411/joost-baaij"
  github        = "https://github.com/spacebabies"
