baseURL = "https://www.spacebabies.nl/"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-us"
paginate = 15
theme = "hugo-creative-portfolio-theme"
title = "Space Babies"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  subtitle = "We create internet"
  description = "Internet Engineers. If you can envision it, we can build it."
  copyright = "Overhoeksplein 2<br>NL-1031KS Amsterdam<br>The Netherlands<br><br>KvK 70132208<br>VAT ID NL001734749B64<br><br><br>"
  sidebarAbout = ["We create beautiful, fast and secure web applications."]
  images = ["img/space-babies.png"]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "info@spacebabies.nl"
  stackoverflow = "https://stackoverflow.com/users/235411/joost-baaij"
  github        = "https://github.com/spacebabies"
