[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "16.18.1"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[context.production.plugins]]
  package = "netlify-plugin-submit-sitemap"

[[context.production.plugins]]
  package = "@netlify/plugin-lighthouse"