[build]
  publish = "public"
  command = "hugo --gc"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "16.18.1"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"