[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=60"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
  
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "max-age=14400"

  for = "/img/*"
  [headers.values]
    Cache-Control = "max-age=14400"

  for = "/*fonts/*"
  [headers.values]
    Cache-Control = "max-age=14400"

  for = "/*.png"
  [headers.values]
    Cache-Control = "max-age=14400"

  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[build]
  publish = "public"
  command = "hugo --baseURL $DEPLOY_URL --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.59.1"

[context.new-2020.environment]
  HUGO_VERSION = "0.75.0"

