[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy-Report-Only = "default-src 'none'; font-src 'self'; img-src 'self'; script-src 'self'; style-src 'self'; report-uri https://spacebabies.report-uri.com/r/d/csp/reportOnly"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://spacebabies.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"


[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "max-age=14400"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[build]
functions = "functions"
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.82.0"
NODE_VERSION = "15"
RUBY_VERSION = "2.7.1"
HUGO_ENABLEGITINFO = "true"

[build.processing]
skip_processing = true

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.82.0"

[[redirects]]
  from = "/portfolio/*"
  to = "/changelog/:splat"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
