[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=60"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
  
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "max-age=14400"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "max-age=14400"

[[headers]]
  for = "/*fonts/*"
  [headers.values]
    Cache-Control = "max-age=14400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "max-age=14400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[build]
  publish = "public"
  command = "hugo --baseURL $DEPLOY_URL --buildDrafts --gc --minify"

[build.environment]
  HUGO_VERSION = "0.75.0"

[build.production]
  command = "hugo --gc --minify"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[redirects]]
  from = "/portfolio/*"
  to = "/changelog/:splat"
  status = 301
  force = true